# Generated by Django 4.1.7 on 2023-03-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitMeApp', '0007_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video File'),
        ),
    ]
